### ISSUE TITLE
JSON error

### ISSUE THREAD

**Issue by RobinDeBaets** [RobinDeBaets/UforaFileFetcher#10]
I randomly got this error when trying to sync:

```
Exception in thread Thread-163:
Traceback (most recent call last):
  File "/usr/lib/python3.8/threading.py", line 932, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.8/threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/local/lib/python3.8/dist-packages/UforaFileFetcher-0.1-py3.8.egg/uff/files.py", line 87, in traverse_element
  File "/usr/local/lib/python3.8/dist-packages/UforaFileFetcher-0.1-py3.8.egg/uff/files.py", line 11, in get_module
  File "/usr/lib/python3/dist-packages/requests/models.py", line 897, in json
    return complexjson.loads(self.text, **kwargs)
  File "/usr/lib/python3/dist-packages/simplejson/__init__.py", line 518, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python3/dist-packages/simplejson/decoder.py", line 370, in decode
    obj, end = self.raw_decode(s)
  File "/usr/lib/python3/dist-packages/simplejson/decoder.py", line 400, in raw_decode
    return self.scan_once(s, idx=_w(s, idx).end())
simplejson.errors.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
```

I imagine it comes from either a server side error or rate limiting. We should implement some additional error handling for this and find a way to move to a thread pool with fixed size.

**Comment by RobinDeBaets** [comment]
Closing this for now, dealing with the error handling later.
