### ISSUE TITLE
 add error handler for (invalid) login inputs

### ISSUE THREAD

**Issue by jessegoeman** [RobinDeBaets/UforaFileFetcher#6]
Stacktrace when entering wrong credentials:

```
Traceback (most recent call last):
  File "./uforafilefetcher", line 4, in <module>
    uforafilefetcher.run()
  File "/media/jesse/HDD/tools/UforaFileFetcher/uforafilefetcher.py", line 29, in run
    setup()
  File "/media/jesse/HDD/tools/UforaFileFetcher/setup.py", line 19, in setup
    session = get_session(username, password)
  File "/media/jesse/HDD/tools/UforaFileFetcher/ufora_login.py", line 11, in get_session
    auth_state = login_html.find("input", {"name": "AuthState"})["value"]
TypeError: 'NoneType' object is not subscriptable
```

**Comment by RobinDeBaets** [comment]
This was due to the broken elosp login, this has been fixed now in c386c9f6a55d5b99c7690138d4c1bbd9b5459996.
